### ISSUE TITLE
File problem

### ISSUE THREAD

**Issue by aybuke-b** [mattkocak/powerbi-visuals-slicerbutton#11]

**Comment by mattkocak** [comment]
Hello, it seems like you've solved the problem, but if not then the beginning of the [Basic Usage](https://www.youtube.com/watch?v=8x2QoE8M2yA&ab_channel=MattKocak) video goes over downloading and importing the visual. Good luck!

**Comment by aybuke-b** [comment]
Helllo Matt, thanks for replying (sorry I didn't know how to delete a comment).

I actually have a problem while trying to use the slicer button. I have a card with a column id, that I filtered with a value from another column. 
I wanted to change this card into a slicer button, so I did it based on the id, and in visual for the 1st column of the table I have, I wrote the value I want to filter with. The problem is that once I click on the button, my table is blank so as the card. Can you help me solve this problem ? Thanks in advance !

**Comment by aybuke-b** [comment]
Sorry to bother you with my questions but I have another one (hopefully).
I quiet understood how the button works I think, but I have a problem. When a column has rows with no value (blank), how do I filter according to these blanks ?

**Comment by mattkocak** [comment]
To filter based on blank values you may want to look into doing this indirectly using a calculated column. It's the same concept that's described in the [Slicing Dates and Complex Logic](https://www.youtube.com/watch?v=_mTS2_dPBZ8&ab_channel=MattKocak) video.

In your case, add a condition to your calculated column that checks whether the value is blank (and whatever other logic you would like) and then output a value of 1 if true, 0 if false. Then use this calculated column with the Slicer Button and a filter value of 1 to get the desired filter effect.

You aren't able to filter on measures, but instead look into using [calculated columns](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-tutorial-create-calculated-columns).

**Comment by aybuke-b** [comment]
Great news! I was able to create a new calculated column in Power BI that evaluates whether a column is blank or not. Thanks for reaching out for help.

I'm still new to Power BI and there are some concepts that I'm not fully familiar with yet, so sorry if my questions seemed basic.

Thanks again for your help and patience. 

Have a great week-end !
