### ISSUE TITLE
Not working when using a Boolean field

### ISSUE THREAD

**Issue by Alexdc-12** [mattkocak/powerbi-visuals-slicerbutton#14]
**Describe the bug**
Within Power BI Desktop November 2023 release this doesnt work when using a Boolean Field

**To Reproduce**
Add Visual
Assign Field of "Current Fiscal Period"
Add Slicer Value "True"
Click on Visual and table refreshes but filter has not been applied

**Expected behavior**
When clicking on visual the table should filter to show all rows where the Current Fiscal Period = True

**Screenshots**

**Desktop (please complete the following information):**
 - Power BI Desktop
 - Power BI Desktop November 2023
 - Browser (if applicable) [e.g. chrome, safari]:

**Additional context**

**Comment by mattkocak** [comment]
Hey Alex, boolean column data types aren't supported, only numbers and strings. However, there is a workaround where you can achieve this by using a **calculated column**.

Essentially, you create a calculated column that returns IF([Current Fiscal Period], 1, 0). Then you instead use this column in the Slicer Button and filter on the returned value of 1. The [Power BI Slicer Button: Slicing Dates and Complex Logic](https://youtu.be/_mTS2_dPBZ8) video goes over a different example, but uses the same concept.

I'm going to close this issue as it isn't a supported feature and I'm not actively working on the project any longer.
